SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        role INTEGER NOT NULL CHECK(role IN (0, 1, 2)),
        pwd_hash TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        refresh_token_hash TEXT UNIQUE,
        expires_at INTEGER,
        revoked BOOLEAN,
        created_at INTEGER
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS tutorDetails (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tutor_id INTEGER REFERENCES users(id),
        rating_sum INTEGER NOT NULL,
        no_ratings INTEGER NOT NULL,
        hourly_gbp INTEGER NOT NULL,
        bio TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS bookings (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tutor_id INTEGER REFERENCES users(id),
        student_id INTEGER REFERENCES users(id),
        start_ts INTEGER NOT NULL,
        end_ts INTEGER NOT NULL,
        notes TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'requested'
              CHECK(status IN ('requested', 'confirmed', 'canceled', 'rejected', 'completed')),
        created_at INTEGER NOT NULL,
        CHECK (end_ts > start_ts)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS tutorSubjects (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tutor_id INTEGER REFERENCES users(id) NOT NULL,
        subject TEXT NOT NULL,
        CONSTRAINT dup_tutor_subject UNIQUE(tutor_id, subject)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS userHours (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER REFERENCES users(id) NOT NULL,
        weekday INTEGER,
        start_s INTEGER NOT NULL,
        end_s INTEGER NOT NULL,
        CONSTRAINT valid_weekday CHECK (weekday BETWEEN 0 AND 6),
        CONSTRAINT dup_user_weekday_hours UNIQUE (user_id, weekday)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS offTimes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER REFERENCES users(id) NOT NULL,
        start_ts INTEGER NOT NULL,
        end_ts INTEGER NOT NULL,
        CONSTRAINT valid_range CHECK (end_ts > start_ts)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reviews (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        booking_id INTEGER UNIQUE REFERENCES bookings(id) NOT NULL,
        tutor_id INTEGER REFERENCES users(id) NOT NULL,
        student_id INTEGER REFERENCES users(id) NOT NULL,
        rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
        comment TEXT,
        created_at INTEGER NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS messages (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        booking_id INTEGER NOT NULL REFERENCES bookings(id),
        user_id INTEGER NOT NULL REFERENCES users(id),
        message TEXT NOT NULL,
        created_at INTEGER NOT NULL
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_messages_booking_created
    ON messages(booking_id, created_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_messages_booking_id
    ON messages(booking_id)
    """,
]
